apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/code-R/argocd-examples
      revision: HEAD
      files:
      - path: services/**/overlays/**/config.json
  template:
    metadata:
      name: '{{name}}-{{namespace}}'
      annotations:    
        argocd-image-updater.argoproj.io/image-list: 'mven/{{docker_image}}'
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: production
      source:
        repoURL: https://github.com/code-R/argocd-examples
        targetRevision: HEAD
        path: '{{ap_path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
        syncOptions:          
          - CreateNamespace=true
