# Source: helm-domain/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-svc-helm-domain
  labels:
    app: helm-domain
    chart: helm-domain-0.1.0
    release: domain-svc
    heritage: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-domain
      release: domain-svc
  template:
    metadata:
      labels:
        app: helm-domain
        release: domain-svc
    spec:
      containers:
        - name: helm-domain
          image: "mven/p-service:sha-83b67df"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}