apiVersion: v1
kind: Service
metadata:
  name: domain-svc-helm-domain
  labels:
    app: helm-domain
    chart: helm-domain-0.1.0
    release: domain-svc
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: helm-domain
    release: domain-svc