# Source: helm-patient/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-svc-helm-patient
  labels:
    app: helm-patient
    chart: helm-patient-0.1.0
    release: patient-svc
    heritage: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-patient
      release: patient-svc
  template:
    metadata:
      labels:
        app: helm-patient
        release: patient-svc
    spec:
      containers:
        - name: helm-patient
          image: "mven/p-service:sha-83b67df"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}